- index.html
> updated social links

- css/custom.css
- css/theme-sulphur.css
- index.html
Fixed the issue #11 by adding a css class, background-image in custom.css and linking it to the index.html file.
Also fixed the problem with hovercard by forcibly fixing its width at 300px.
Before:
After:
> Fixed Mentor Images scaling problem

- index.html
> Add the-dagger's links

- index_cn.html
@hpdang A simple translation of the page. Please check it ASAP so that I could start advertising this competition in my community.
> Add simple translated Chinese index page(FAQ translation not included)

- index.html
added my github,twitter,facebook profile links WRT issue #2  .
> Added my profile links.

- index.html
Reverts fossasia/codeheat.org#27
> Revert "Added my profile links."

- index.html
> Add social network links

- index.html
> Error in spelling of Sayan

- index.html
Mayank tripathi asked me to update his facebook id.
> Added facebook id mayank

- index.html
Fixes #36 - Sets correct link for Pocket Science lab projects in index.html
> Set correct link for Pocket Science lab projects.

- index.html
Previously, no breaks were added. I also added the links to the FOSSASIA's and loklak's github profile!
> Added more links and fixed some breakline issues

- index.html
This issue has been fixed. Screenshot attached below.
[Pull Request Details](https://sounak98.github.io/fossasia.html)
> Fixes #47 to fix alignment of icons in the front page

- README.md
Information about Development workflow for new contributors is added in README
> Adding contribution guidelines in README

- css/theme-sulphur.css
@isuruAb I have added the media queries. The background image works perfectly fine locally, but for some reason not on gh-pages. Please review. Thanks !
https://parimatrix.github.io/codeheat.org/
> Center Align the Speaker info for mobile screens

- index.html
Added personal website info and edited description info
> Added website and description

- css/theme-sulphur.css
- index.html
Fix #78 
@hpdang The issue was because of some extra content in some of the project divs. I assigned a min-height to it to prevent the issue in the placement of the project divs.
Please review the changes here: http://codeheat.bitballoon.com/
Thanks
PS: This was an issue with every browser.
> Fix Positioning

- index.html
> Add project to list

- index.html
Other sites of FOSSASIA has info with stats like the number of mentors,
students and pull request. So, implemented same for codeheat site.
Closes #110
Preview Link: https://ankurg22.github.io/codeheat.org/
> Added info section below the header

- index.html
> Update contact info of Ritika Motwani

- index.html
> Add anshumanv in mentors list

- index.html
> Add Akshat-Jain to mentor list

- index.html
This PR adds Sanskar to the mentor list
> Add Sanskar to the mentor list

- index.html
This PR adds me as codeheat mentor
> Add Mohit Sharma as Mentor

- index.html
-> The div row component was missing in the "MENTORS" section and also was not properly ended.
-> <p> was not closed in the body of "Meilix" in the "PROJECTS" section.
> Fix div component missing and <p> was not properly ended

- index.html
> Changed year in timeline section.

- index.html
Closes https://github.com/fossasia/codeheat.org/issues/134
> Change year to 2019 in timeline

- index.html
> fix(index): Corrected start date of competition

- index.html
> Fix the link for badgeyay mailing list

- index.html
fixed mentors layout problem .
Before ,
After,
fixed it.
> fixed  the mentors layout problem

- index.html
> fixed  : SUSI.AI for magic minnor project , link's margin problem 

- index.html
Fixes #179 
- Added correct chat link for badgeyay project
> Added badgeyay projects correct chat link

- index.html
> Added my college's name

- index.html
Fixes #186
Fixes the participants participated and year specified in Codeheat
> Correct participants data in codeheat

- index.html
> Fix: Remove Codeheat 2019 from about section #210 

- index.html
Fixes some typos in on the codeheat [website](https://codeheat.org/)
Below is the screenshot of few such typing mistake
Before
After
> Fixes typos in timeline

- index.html
Corrected spelling mistake in PSlab Android 
Fixes #273
> Updated spelling mistake

- README.md
- css/theme-camaro.css
fixed the overlapping of the navbar see in the screenshot for the better understanding.....
#244
> Fix: the overlapping of the elements in navbar

- index.html
Fixed Copyright in footer  . As mentioned in the #312 issue .
> Updated - index.html

- README.md
Updated & structured the README file by following the content of other README files in fossasia repos
> [docs] Updated README file

- css/theme-sulphur.css
fix(ui): Removed extra white space on mobile devices( #329 )
> fix(ui): removed extra white space on mobile devices

- index.html
> fix image alignment

- index.html
What does the PR do?
1. Remove trailing slash on void elements 
`<meta property="og:type" content="website" /> `
-> `<meta property="og:type" content="website">`
2. Refactoring to improve readability
3. Fix typos
By submitting this pull request, I confirm that my contribution is made under the terms of the AGPL-3.0 License.
> Refactor index page

- index.html
> fix: copyright year updated
